version: '2'

services:
  nginx:
    build: ./.docker/nginx
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/hosts/site.conf:/etc/nginx/conf.d/site.conf
      - ./:/var/www
      - ./.docker/nginx/logs:/var/log/nginx
    links:
      - php
  php:
    build: ./.docker/php
    volumes:
      - ./:/var/www